### ISSUE TITLE
Feature Request: Chaining modals (queue) example : Is there any way to get value of inputs in each  step

### ISSUE THREAD

**Issue by gssumesh** [limonte/sweetalert2#331]
I am not sure if this is a feature or an enhancement request. Chaining modals (queue) example : Is there any way to get value of inputs in each  steps in Final then() which alerts the All Done! in example. Thanks!

**Comment by limonte** [comment]
Thank you @gssumesh for requesting this!

Done in [v5.3.6](https://github.com/limonte/sweetalert2/releases/tag/v5.3.6)

See the example: https://limonte.github.io/sweetalert2/#chaining-modals

**Comment by gssumesh** [comment]
Wow that was quick !!! 👍  . I believe you might need to update the example as swal.queue(steps).then(function(**result**) {
You missed, result in input function. But anyways, thanks a lot for quick turn around!!!! :)

**Comment by limonte** [comment]
> I believe you might need to update the example as swal.queue(steps).then(function(result) {

Oops, fixed. Thanks :+1:

**Comment by mayeaux** [comment]
It's a dead link now

**Comment by limonte** [comment]
> It's a dead link now

here's the updated one https://sweetalert2.github.io/#chaining-modals

**Comment by mayeaux** [comment]
Thanks
