### ISSUE TITLE
"Success" dialogs with background color look off

### ISSUE THREAD

**Issue by NiExTy** [limonte/sweetalert2#491]
Try this example:

```
swal({
  background: 'purple',
  type: 'success'
})
```

http://pix.toile-libre.org/upload/original/1491399056.png

**Comment by limonte** [comment]
Thanks @NiExTy for reporting this issue. Here's the jsfiddle demonstrating it: https://jsfiddle.net/ad3quksn/83/

I'll fix this asap :rocket:

**Comment by limonte** [comment]
Fixed in [v6.6.0](https://github.com/limonte/sweetalert2/releases/tag/v6.6.0), thanks for reporting!

**Comment by NiExTy** [comment]
Still not perfect with more complex backgrounds:

```
swal({
  background: 'rgba(0,0,0,0) linear-gradient(#444,#111) repeat scroll 0 0',
  type: 'success'
})
```

http://pix.toile-libre.org/upload/original/1491667358.png

**Comment by NiExTy** [comment]
Any fix for that @limonte?

**Comment by voldemortkein** [comment]
@limonte Thanks, now It works as you said, that was fixed on v.6.6.0.
In order to work properly is important not to have tweaked extra css like me.

I have this:
```
.swal-modal {
 background-color: darkorange;
}
```

And works, but not at all, cuz Success animation have this issue.
So, then the solution is remove that in my personal CSS stylesheet.

but I need to specify on every swal of my project, the color desired, like this:
```
swal({
  background: 'purple',
  type: 'success'
})
```


But what about if I have a lot of Swal alerts?, Is there a way to set the SweetAlert's background color on css stylesheet?


Thanks.
And Nice Software!!

**Comment by lakshitha1629** [comment]
Use this CSS code to change success icon color mixing issue

.swal2-icon.swal2-success::before,
.swal2-success.animate::after,
.swal2-icon.swal2-success .fix{
	background-color: rgb(22 22 22) !important;
}
